controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

generate_qr:
    path: /generate-qr
    controller: App\Controller\QrCodeController::generateQrCode